### ISSUE TITLE
Add the transaction hash with a link to Voyager when linking an Github account

### ISSUE THREAD

**Issue by pacovilletard** [onlydustxyz/marketplace-frontend#113]
When I want to connect a Github account to my OnlyDust profil I had to send a message to validate my wallet and wait for the transaction to be approved. It takes time on Starknet. We need to give some feedback to the user.

During the registration process we need to show the status of the following steps to the user :

- Github account validation process
- Transaction (with the hash and link to Voyager and a estimated remaining time (can be hardcoded, no need to be precise here))

![Screenshot 2022-08-31 at 15 56 45](https://user-images.githubusercontent.com/98735421/187696546-d18b7486-6a01-47f6-b27c-d3400d6317be.png)

**Comment by ltoussaint** [comment]
Closed by #158
