### ISSUE TITLE
[FEAT] project page - show 'looking for contributors' projects only

### ISSUE THREAD

**Issue by remybar** [onlydustxyz/marketplace-frontend#1787]
As a developer looking for some projects to contribute to, I would appreciate being able to filter projects which actively looking for contributors only (i.e projects with the tag "looking for contributors").

Would it be possible to add this filter ? 

I can try to implement it if needed !

**Comment by GregGamb** [comment]
Hi @remybar! It's Greg (CEO OnlyDust), amazing feedback. We are working on it; we want to create a better onboarding and searching experience on the platform; it's our big subject of the quarter.

**Comment by remybar** [comment]
Awesome !

**Comment by ktarun1419** [comment]
Hi @GregGamb i want to work on this issue

**Comment by GregGamb** [comment]
Hi @ktarun1419 , we have created a new filter, this issue is no longer useful. Thank you @remybar for the idea ;)

**Comment by remybar** [comment]
> Hi @ktarun1419 , we have created a new filter, this issue is no longer useful. Thank you @remybar for the idea ;)

Oups, sorry, I forgot to close it 😅  Thanks for the new filters 🙏
