### ISSUE TITLE
GFI : Upgrade to Protostar 0.4.2 Context: coupled interact with some parts of the codebase

### ISSUE THREAD

**Issue by pixelfact** [onlydustxyz/marketplace-frontend#2328]
Describe the Feature Request 
Once we have Declare V2 implemented from this #744, we will need a way to store the Sierra program which is passed from the RPC call. Right now, the Sierra program isn't stored anywhere and so we aren't able to return it when the user calls get_class_at. When storing this mapping, we must do it in a way that it is communicated to all the other nodes.

Describe Preferred Solution

We can implement this in the run time but that should be our last option as the runtime should only have the information needed for the chain state. The Sierra program is not essential for the chain state and so we must store them elsewhere. The db in the client isn't gossiped between the nodes and is a local copy. So we need to explore how we can get this done.

If the feature request is approved, would you be willing to submit a PR?
(Help can be provided if you need assistance submitting a PR) 
Yes

**Comment by haydencleary** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by haydencleary** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by haydencleary** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by AnthonyBuisset** [comment]
I can do it!

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by haydencleary** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by pixelfact** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com).

**Comment by PaulDemOD** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com).

**Comment by PaulDemOD** [comment]
I am applying to this issue via [OnlyDust platform](https://staging-app.onlydust.com/p/bretzel).

### My background and how it can be leveraged
Test QA de la partie du BE de Antho !

### How I plan on tackling this issue
Si ca marche pas c'est pas cool

**Comment by alexbeno** [comment]
I am applying to this issue via [OnlyDust platform](https://develop-app.onlydust.com/p/onlydust).

### My background and how it can be leveraged
aa

### How I plan on tackling this issue
aa

**Comment by od-hunter** [comment]
Hello @pixelfact , is this issue closed yet? If no, can I be assigned please?
