### ISSUE TITLE
Integrate Braavos wallet

### ISSUE THREAD

**Issue by Bernardstanislas** [onlydustxyz/marketplace-frontend#93]
## Statement

Current platform is only compatible with ArgentX wallet.
This is not suitable, we want to cover most of the ecosystems wallet, so the next step is to integrate Braavos wallet.

## What is expected

A clean and tested integration of this second wallet, you might need a modal to let the user choose between both, designs are expected to be "best efforts" on this subject.

**Comment by ltoussaint** [comment]
closed by #99
