### ISSUE TITLE
Handle "contribution not found" on contribution details page

### ISSUE THREAD

**Issue by ltoussaint** [onlydustxyz/marketplace-frontend#97]
## Statement

When going on a contribution details page with and contribution id which does not exist, we see a blank page.
Example of url with an id which does not exist : [https://app.onlydust.xyz/contributions/012346789](https://app.onlydust.xyz/contributions/012346789)

## What is expected

Display an error message telling this contribution does not exists.
Add a link to go back (go to the previous page)

_You can copy the style of the component `ErrorFallback` component_

**Comment by Bernardstanislas** [comment]
Closed by #101
