### ISSUE TITLE
Handle "project not found" on project details page

### ISSUE THREAD

**Issue by ltoussaint** [onlydustxyz/marketplace-frontend#98]
## Statement

When going on a project details page with a project id which does not exist, we see a blank page.
Example of url with an id which does not exist : [https://app.onlydust.xyz/projects/012346789](https://app.onlydust.xyz/projects/012346789)

## What is expected

Display an error message telling this project does not exists.
Add a link to go back (go to the previous page)

_You can copy the style of the component `ErrorFallback` component_

**Comment by Bernardstanislas** [comment]
Closed by #101
